version: '3.0'

services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      PSQL_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud_nest
      DATABASE_URL: postgres://postgres:admin@localhost:5432/crud_nest
      NODE_ENV: development
      PORT: 7000
    ports:
      - "7000:7000"
    command: npm run start:dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres:10.4
    ports:
      - "3000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crud_nest

volumes:
  postgres:
